import type { BrainDocument } from "./types";

const today = "2026-09-08";

type SheetEmployee = {
  serialNo: number;
  name: string;
  phone?: string;
  role: string;
  department: string;
  dateOfLeaving: string;
  currentSalary: string;
  updatedStipend: string;
  dateOfJoining: string;
  oldStipend: string;
  offerLetter: string;
  panCard: string;
  aadhaarCard: string;
  bankDetails: string;
  paidFebStipend: string;
  paidMarch7: string;
  paidFeb3: string;
  paidMay7: string;
  paidJun5: string;
};

const employees: SheetEmployee[] = [
  {
    serialNo: 1,
    name: "Yash Tandon",
    phone: "+91 70567 54400",
    role: "Founder & CEO",
    department: "Executive",
    dateOfLeaving: "Still Active",
    currentSalary: "80000",
    updatedStipend: "80k",
    dateOfJoining: "01/01/2025",
    oldStipend: "50k",
    offerLetter: "",
    panCard: "Yash Pan.pdf",
    aadhaarCard: "Yash Aadhar.pdf",
    bankDetails: "Yash Account",
    paidFebStipend: "Yes",
    paidMarch7: "80000",
    paidFeb3: "50000",
    paidMay7: "80000",
    paidJun5: "80000"
  },
  {
    serialNo: 2,
    name: "Riya Kapoor",
    phone: "+91 98765 43210",
    role: "Operations Lead",
    department: "Operations",
    dateOfLeaving: "Still Active",
    currentSalary: "45000",
    updatedStipend: "45k",
    dateOfJoining: "15/02/2025",
    oldStipend: "30k",
    offerLetter: "Riya - ComBrain AI Offer letter.pdf",
    panCard: "Riya Pan.pdf",
    aadhaarCard: "Riya Aadhar.pdf",
    bankDetails: "Riya Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "45000",
    paidFeb3: "30000",
    paidMay7: "45000",
    paidJun5: "45000"
  },
  {
    serialNo: 3,
    name: "Aarav Deshmukh",
    phone: "+91 91234 56789",
    role: "Full Stack Developer",
    department: "Engineering",
    dateOfLeaving: "Still Active",
    currentSalary: "35000",
    updatedStipend: "35k",
    dateOfJoining: "01/03/2025",
    oldStipend: "22k",
    offerLetter: "Aarav - ComBrain AI Offer letter.pdf",
    panCard: "Aarav Pan.pdf",
    aadhaarCard: "Aarav Aadhar.pdf",
    bankDetails: "Aarav Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "35000",
    paidFeb3: "22000",
    paidMay7: "35000",
    paidJun5: "35000"
  },
  {
    serialNo: 4,
    name: "Tanvi Reddy",
    phone: "+91 87654 32109",
    role: "AI/ML Engineer",
    department: "Engineering",
    dateOfLeaving: "Still Active",
    currentSalary: "40000",
    updatedStipend: "40k",
    dateOfJoining: "10/03/2025",
    oldStipend: "25k",
    offerLetter: "Tanvi - ComBrain AI Offer letter.pdf",
    panCard: "Tanvi Pan.pdf",
    aadhaarCard: "Tanvi Aadhar.pdf",
    bankDetails: "Tanvi Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "40000",
    paidFeb3: "25000",
    paidMay7: "40000",
    paidJun5: "40000"
  },
  {
    serialNo: 5,
    name: "Harsh Gupta",
    phone: "+91 99887 76655",
    role: "Backend Developer",
    department: "Engineering",
    dateOfLeaving: "Still Active",
    currentSalary: "28000",
    updatedStipend: "28k",
    dateOfJoining: "20/04/2025",
    oldStipend: "18k",
    offerLetter: "Harsh - ComBrain AI Offer letter.pdf",
    panCard: "Harsh Pan.pdf",
    aadhaarCard: "Harsh Aadhar.pdf",
    bankDetails: "Harsh Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "28000",
    paidFeb3: "18000",
    paidMay7: "28000",
    paidJun5: "28000"
  },
  {
    serialNo: 6,
    name: "Simran Kaur",
    phone: "+91 77665 54433",
    role: "UI/UX Designer",
    department: "Design",
    dateOfLeaving: "Still Active",
    currentSalary: "30000",
    updatedStipend: "30k",
    dateOfJoining: "01/05/2025",
    oldStipend: "20k",
    offerLetter: "Simran - ComBrain AI Offer letter.pdf",
    panCard: "Simran Pan.pdf",
    aadhaarCard: "Simran Aadhar.pdf",
    bankDetails: "Simran Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "30000",
    paidFeb3: "20000",
    paidMay7: "30000",
    paidJun5: "30000"
  },
  {
    serialNo: 7,
    name: "Vikram Chauhan",
    phone: "+91 88990 01122",
    role: "Sales Executive",
    department: "Sales",
    dateOfLeaving: "Still Active",
    currentSalary: "25000",
    updatedStipend: "25k",
    dateOfJoining: "15/05/2025",
    oldStipend: "15k",
    offerLetter: "Vikram - ComBrain AI Offer letter.pdf",
    panCard: "Vikram Pan.pdf",
    aadhaarCard: "Vikram Aadhar.pdf",
    bankDetails: "Vikram Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "25000",
    paidFeb3: "15000",
    paidMay7: "25000",
    paidJun5: "25000"
  },
  {
    serialNo: 8,
    name: "Neha Saxena",
    phone: "+91 99001 12233",
    role: "Content & Marketing",
    department: "Marketing",
    dateOfLeaving: "15/07/2026",
    currentSalary: "",
    updatedStipend: "-",
    dateOfJoining: "01/06/2025",
    oldStipend: "15k",
    offerLetter: "Neha - ComBrain AI Offer letter.pdf",
    panCard: "Neha Pan.pdf",
    aadhaarCard: "Neha Aadhar.pdf",
    bankDetails: "Neha Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "15000",
    paidFeb3: "15000",
    paidMay7: "15000",
    paidJun5: "15000"
  },
  {
    serialNo: 9,
    name: "Rohit Malhotra",
    phone: "+91 88776 65544",
    role: "DevOps Engineer",
    department: "Engineering",
    dateOfLeaving: "Still Active",
    currentSalary: "32000",
    updatedStipend: "32k",
    dateOfJoining: "10/06/2025",
    oldStipend: "20k",
    offerLetter: "Rohit - ComBrain AI Offer letter.pdf",
    panCard: "Rohit Pan.pdf",
    aadhaarCard: "Rohit Aadhar.pdf",
    bankDetails: "Rohit Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "32000",
    paidFeb3: "20000",
    paidMay7: "32000",
    paidJun5: "32000"
  },
  {
    serialNo: 10,
    name: "Ananya Bhat",
    phone: "+91 77889 90011",
    role: "Prompt Engineer",
    department: "AI Delivery",
    dateOfLeaving: "Still Active",
    currentSalary: "26000",
    updatedStipend: "26k",
    dateOfJoining: "01/07/2025",
    oldStipend: "16k",
    offerLetter: "Ananya - ComBrain AI Offer letter.pdf",
    panCard: "Ananya Pan.pdf",
    aadhaarCard: "Ananya Aadhar.pdf",
    bankDetails: "Ananya Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "26000",
    paidFeb3: "16000",
    paidMay7: "26000",
    paidJun5: "26000"
  },
  {
    serialNo: 11,
    name: "Ishaan Pillai",
    phone: "+91 96543 21098",
    role: "Data Analyst",
    department: "Analytics",
    dateOfLeaving: "Still Active",
    currentSalary: "24000",
    updatedStipend: "24k",
    dateOfJoining: "15/07/2025",
    oldStipend: "15k",
    offerLetter: "Ishaan - ComBrain AI Offer letter.pdf",
    panCard: "Ishaan Pan.pdf",
    aadhaarCard: "Ishaan Aadhar.pdf",
    bankDetails: "Ishaan Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "24000",
    paidFeb3: "15000",
    paidMay7: "24000",
    paidJun5: "24000"
  },
  {
    serialNo: 12,
    name: "Pooja Menon",
    phone: "+91 85432 10987",
    role: "Customer Success",
    department: "Customer Success",
    dateOfLeaving: "Still Active",
    currentSalary: "22000",
    updatedStipend: "22k",
    dateOfJoining: "01/08/2025",
    oldStipend: "14k",
    offerLetter: "Pooja - ComBrain AI Offer letter.pdf",
    panCard: "Pooja Pan.pdf",
    aadhaarCard: "Pooja Aadhar.pdf",
    bankDetails: "Pooja Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "22000",
    paidFeb3: "14000",
    paidMay7: "22000",
    paidJun5: "22000"
  },
  {
    serialNo: 13,
    name: "Dev Agarwal",
    phone: "+91 93210 98765",
    role: "Mobile Developer",
    department: "Engineering",
    dateOfLeaving: "28/06/2026",
    currentSalary: "",
    updatedStipend: "-",
    dateOfJoining: "20/08/2025",
    oldStipend: "18k",
    offerLetter: "Dev - ComBrain AI Offer letter.pdf",
    panCard: "Dev Pan.pdf",
    aadhaarCard: "Dev Aadhar.pdf",
    bankDetails: "Dev Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "18000",
    paidFeb3: "18000",
    paidMay7: "18000",
    paidJun5: ""
  },
  {
    serialNo: 14,
    name: "Kriti Sharma",
    phone: "+91 81098 76543",
    role: "QA Engineer",
    department: "Engineering",
    dateOfLeaving: "Still Active",
    currentSalary: "20000",
    updatedStipend: "20k",
    dateOfJoining: "01/09/2025",
    oldStipend: "12k",
    offerLetter: "Kriti - ComBrain AI Offer letter.pdf",
    panCard: "Kriti Pan.pdf",
    aadhaarCard: "Kriti Aadhar.pdf",
    bankDetails: "Kriti Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "20000",
    paidFeb3: "12000",
    paidMay7: "20000",
    paidJun5: "20000"
  },
  {
    serialNo: 15,
    name: "Siddharth Jain",
    phone: "+91 70987 65432",
    role: "Business Development",
    department: "Sales",
    dateOfLeaving: "Still Active",
    currentSalary: "27000",
    updatedStipend: "27k",
    dateOfJoining: "15/09/2025",
    oldStipend: "17k",
    offerLetter: "Siddharth - ComBrain AI Offer letter.pdf",
    panCard: "Siddharth Pan.pdf",
    aadhaarCard: "Siddharth Aadhar.pdf",
    bankDetails: "Siddharth Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "27000",
    paidFeb3: "17000",
    paidMay7: "27000",
    paidJun5: "27000"
  },
  {
    serialNo: 16,
    name: "Megha Tiwari",
    phone: "+91 60876 54321",
    role: "HR & Admin",
    department: "People",
    dateOfLeaving: "Still Active",
    currentSalary: "23000",
    updatedStipend: "23k",
    dateOfJoining: "01/10/2025",
    oldStipend: "15k",
    offerLetter: "Megha - ComBrain AI Offer letter.pdf",
    panCard: "Megha Pan.pdf",
    aadhaarCard: "Megha Aadhar.pdf",
    bankDetails: "Megha Cheque",
    paidFebStipend: "Yes",
    paidMarch7: "23000",
    paidFeb3: "15000",
    paidMay7: "23000",
    paidJun5: "23000"
  },
];

const slugify = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const normalizeStatus = (dateOfLeaving: string): "Active" | "Exited" =>
  dateOfLeaving === "Still Active" ? "Active" : "Exited";

export const sheetEmployeeDocuments: BrainDocument[] = employees.map((emp) => {
  const status = normalizeStatus(emp.dateOfLeaving);
  const docId = `emp-sheet-${slugify(emp.name)}`;
  const paymentSummary = [
    emp.paidFebStipend ? `- Paid Feb stipend: ${emp.paidFebStipend}` : "",
    emp.paidMarch7 ? `- Paid March 7: ${emp.paidMarch7}` : "",
    emp.paidFeb3 ? `- Paid Feb 3: ${emp.paidFeb3}` : "",
    emp.paidMay7 ? `- Paid May 7: ${emp.paidMay7}` : "",
    emp.paidJun5 ? `- Paid Jun 5/6: ${emp.paidJun5}` : "",
  ].filter(Boolean).join("\n");

  return {
    id: docId,
    type: "employee",
    title: `${emp.name} - ${emp.role}`,
    status,
    owner: "Founder Office",
    updatedAt: today,
    tags: ["employee", emp.department, status],
    fields: {
      serialNo: `${emp.serialNo}`,
      name: emp.name,
      role: emp.role,
      department: emp.department,
      monthlySalaryInr: emp.currentSalary ? parseInt(emp.currentSalary.replace(/\D/g, "")) || 0 : 0,
      currentSalaryRaw: emp.currentSalary || "",
      updatedStipendRaw: emp.updatedStipend || "",
      oldStipendRaw: emp.oldStipend || "",
      dateOfJoining: emp.dateOfJoining,
      dateOfLeaving: emp.dateOfLeaving === "Still Active" ? "" : emp.dateOfLeaving,
      status,
      phone: emp.phone || "",
      location: "India",
      reportingTo: "Founder",
      offerLetter: emp.offerLetter,
      offerLetterStatus: emp.offerLetter ? "Available" : "Missing",
      panCard: emp.panCard,
      panCardStatus: emp.panCard ? "Available" : "Missing",
      aadhaarCard: emp.aadhaarCard,
      aadhaarCardStatus: emp.aadhaarCard ? "Available" : "Missing",
      bankDetails: emp.bankDetails,
      bankDetailsStatus: emp.bankDetails ? "Available" : "Missing",
    },
    body: `Employee record for ${emp.name}.\n\nRole: ${emp.role}\nDepartment: ${emp.department}\nStatus: ${status}\nDate of joining: ${emp.dateOfJoining}\nDate of leaving: ${emp.dateOfLeaving}\nCurrent salary: ${emp.currentSalary || "N/A"}\nUpdated stipend: ${emp.updatedStipend}\nOld stipend: ${emp.oldStipend}\n\nDocument references:\n- Offer letter: ${emp.offerLetter || "Not uploaded"}\n- PAN card: ${emp.panCard}\n- Aadhaar card: ${emp.aadhaarCard}\n- Bank details: ${emp.bankDetails || "Protected"}\n\nPayment records:\n${paymentSummary || "- No payment records"}`,
  };
});
